from sqlalchemy import Boolean, Column, Date, DateTime, Integer, Numeric, String, Text
from models.base import Base


class Partner(Base):
    __tablename__ = "res_partner"

    id = Column(Integer, primary_key=True)
    company_id = Column(Integer)
    title = Column(Integer)
    parent_id = Column(Integer)
    user_id = Column(Integer)
    state_id = Column(Integer)
    country_id = Column(Integer)
    industry_id = Column(Integer)
    commercial_partner_id = Column(Integer)
    create_uid = Column(Integer)
    write_uid = Column(Integer)
    branch_id = Column(Integer)
    education_level_id = Column(Integer)
    kyc_limit_id = Column(Integer)
    tier_id = Column(Integer)
    identification_type_id = Column(Integer)
    region_id = Column(Integer)
    sector_id = Column(Integer)
    customer_industry_id = Column(Integer)
    sex_id = Column(Integer)
    account_officer_id = Column(Integer)
    risk_level_id = Column(Integer)
    global_pep_id = Column(Integer)
    message_main_attachment_id = Column(Integer)
    message_bounce = Column(Integer)
    color = Column(Integer)

    create_date = Column(DateTime)
    write_date = Column(DateTime)
    signup_expiration = Column(DateTime)
    date = Column(Date)

    name = Column(String)
    display_name = Column(String)
    ref = Column(String)
    lang = Column(String)
    tz = Column(String)
    vat = Column(String)
    company_registry = Column(String)
    website = Column(String)
    function = Column(String)
    type = Column(String)
    street = Column(String)
    street2 = Column(String)
    zip = Column(String)
    city = Column(String)
    email = Column(String)
    phone = Column(String)
    mobile = Column(String)
    commercial_company_name = Column(String)
    company_name = Column(String)
    email_normalized = Column(String)
    signup_type = Column(String)
    signup_token = Column(String)
    customer_id = Column(String)
    bvn = Column(String)
    identification_number = Column(String)
    firstname = Column(String)
    short_name = Column(String)
    lastname = Column(String)
    middlename = Column(String)
    othername = Column(String)
    town = Column(String)
    risk_level = Column(String)
    internal_category = Column(String)
    anti_bribery_file_name = Column(String)
    data_protection_file_name = Column(String)
    whistle_blowing_file_name = Column(String)
    anti_money_laundering_file_name = Column(String)
    address = Column(String)
    customer_title = Column(String)
    gender = Column(String)
    marital_status = Column(String)
    employment_status = Column(String)
    state_residence = Column(String)

    comment = Column(Text)

    partner_latitude = Column(Numeric)
    partner_longitude = Column(Numeric)

    active = Column(Boolean)
    employee = Column(Boolean)
    is_company = Column(Boolean)
    partner_share = Column(Boolean)
