{
    'name': 'iComply ETL Manager',
    'version': '1.0',
    'category': 'iComply',
    'summary': 'Manage ETL configurations and processes',
    'sequence': 1,
    'author': 'Novaji Introserve Ltd',
    'website': 'https://www.novajii.com',
    'depends': ['base', 'mail'],
    'data': [
        'security/ir.model.access.csv',
        'data/etl_default_data.xml',
        'views/etl_sync_log_views.xml',
        'views/etl_config_views.xml',
        'views/etl_dashboard.xml',
        'views/etl_menu.xml',
        'data/etl_cron.xml',
        'data/etl_data.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}