[database]
host = 172.20.160.111
port = 5432
user = icompy_novaji_user
password = icompy_novaji1234567
dbname = iComply

[operation_1]
name = set_customer_to_pep
type = UPDATE
table = res_partner
condition = trim(upper(pep)) = 'YES' AND (is_pep IS NULL OR is_pep = False)
set_clause = is_pep = True
batch_size = 5000
sleep_time = 2.0

[operation_2]
name = set_customer_origin
type = UPDATE
table = res_partner
condition = customer_id IS NOT NULL AND origin IS NULL
set_clause = origin = 'test'
batch_size = 5000
sleep_time = 2.0

[settings]
batch_size = 1000
lock_timeout = 5000
num_workers = 3

[tables]
res_pep = first_name,surname,name

[csv]
path = /data/odoo/ETL_script/update_script/csv_data
force_regeneration = False

[processing]
batch_size = 5000
num_workers = 5
checkpoint_interval = 5
log_interval = 30
checkpoint_file = risk_calculation_checkpoint.json

