[options]
db_host = localhost
db_user = magpora_user
db_password = magpora_mpr9090
db_name = icomply_odoo
addons_path = /home/gbemi/odoo/addons,/home/gbemi/odoo/addons/icomply_odoo 
default_productivity_apps = True
logfile = /home/gbemi/odoo/addons/icomply_odoo/icomply.log
xmlrpc_port = 8077
xmlrpcs = True

# password Testing123!
# user admin
# ezekiel.k@novajii.com
