[options]
db_host = localhost
db_port = 5432
db_user = user
db_password = newpassword
# db_name = all_databases
db_name = rule_book_db
# db_name = all_database
addons_path = addons,Ajeh,AccueStock,Lapo,icomply,gopher_wood_app,vista_backend_theme
default_productivity_apps = True
logfile = /Users/user/Development/erp/myOdoo/gopher_wood_project/icomply/rule_book/rule_book.log
# workers=2
# http_port = 8069
# ws_port = 8073
# max_cron_threads = 1
# workers = 4
# ; Set session timeout to 24 hours (default is 1 hour)
# session.timeout = 1440
# admin_passwd = $pbkdf2-sha512$600000$TMnZmzNmLIXQGuOc05qzNg$X55xJAEc4HhS1NedfAwSkAVIMNf7UincQ301Q3QZY7xiSljhQKYlbMeEXDfV/3yr7fQWzDgCU3LoQuq/N22/yQ

#./odoo-bin  --database=general_databases  --db_user=user  --db_host=localhost --db_port=5432 --db_password=new-password -i INIT
# general_databases master password: Damilola&*0
# user admin password user-password
# start up for odoo ./odoo-bin -c /Users/user/Development/erp/myOdoo/gopher_wood_project/odoo.conf -u users   
# start up for websocket  python /Users/user/Development/erp/myOdoo/gopher_wood_project/realTimecommuniction/websocket/server.py

# second db for gopher wood app: rule_book_db
# user admin, password user-password
# for running rule book db ./odoo-bin -c odoo.conf --db-filter=gopher_wood_app --xmlrpc-port=8070 -u school_management,school_management_teacher



# server details
# email Komolafeezekiel123@gmail.com
# password Testing123! (there is a space before the password)
# db gopher_wood_app




