from odoo import models, fields

class UserProfile(models.Model):
    _inherit = "res.users"
    _description = 'User Profile'
    

    # Define the fields based on the SQL query provided
    department = fields.Many2one("hr.department",string="Department Code")
    # login_status = fields.Boolean(string="Login Status", default=False)
    # authoriser = fields.Integer(string="Authoriser")
    # branch_code = fields.Char(string="Branch Code")
    # staff_status = fields.Char(string="Staff Status")
    # post_gl_acctno = fields.Char(string="Post GL Account Number")
    # passchange_date = fields.Datetime(string="Password Change Date")
    # next_passchange_date = fields.Datetime(string="Next Password Change Date")
    # create_date = fields.Datetime(string="Creation Date")
    # ss_code = fields.Integer(string="SS Code")
    # session_id = fields.Char(string="Session ID")
    # computer_name = fields.Char(string="Computer Name")
    # mach_address = fields.Char(string="Machine Address")
    # lock_count = fields.Integer(string="Lock Count")
    # report_level = fields.Integer(string="Report Level")
    # auth_user_id = fields.Char(string="Auth User ID")
    # post_user_id = fields.Char(string="Post User ID")
    # phone_no = fields.Char(string="Phone Number")
    # status = fields.Integer(string="Status")
    # auth_id = fields.Integer(string="Auth ID")
    # sms_alert = fields.Integer(string="SMS Alert")
    # email_alert = fields.Integer(string="Email Alert")
    # offline_alert = fields.Integer(string="Offline Alert")
    # authorised_by = fields.Char(string="Authorised By")
    # enforce_pwd = fields.Integer(string="Enforce Password Change")
    # exempt_lock = fields.Integer(string="Exempt Lock")
    # statement = fields.Char(string="Statement")
    # remote_login = fields.Integer(string="Remote Login")
    # target_amt = fields.Float(string="Target Amount")
    # login_count = fields.Integer(string="Login Count")
    # multi_login = fields.Integer(string="Multi Login")
    # sbu = fields.Char(string="SBU")
    # report_flag = fields.Integer(string="Report Flag")
    # resume_date = fields.Datetime(string="Resume Date")
    # daon_user_id = fields.Char(string="Daon User ID")
    # daon_reg_id = fields.Char(string="Daon Reg ID")
    # daon_created = fields.Datetime(string="Daon Created Date")
    # daon_channel = fields.Char(string="Daon Channel")
    # daon_auth_req = fields.Integer(string="Daon Auth Request")
