# -*- coding: utf-8 -*-

from . import branch
from . import education_level
from . import customer_tier
from . import kyc_limit
from . import identification_types
from . import marital_status
from . import customer_sector
from . import region
from . import account_ledger
from . import account_product
from . import gender
from . import risk_level
from . import users
from . import customer
from . import customer_account_type
from . import customer_account
from . import risk_assessment_type
from . import risk_category
from . import risk_subject
from . import risk_type
from . import risk_universe
from . import risk_assessment
from . import risk_assessment_line
from . import pep
from . import edd
from . import feplist
from . import blacklist
from . import watchlist
from . import statistic